rvm: 2.2.3
sudo: false
cache: bundler
addons:
  apt:
    sources:
    - elasticsearch-2.1
    packages:
    - elasticsearch
services:
  - elasticsearch
before_script:
  - cp test/dummy/.env.example test/dummy/.env
  - bundle exec rake app:db:setup
  - bundle exec rake app:index:reset
  - curl localhost:9200
