rvm: 2.2.3
sudo: false
cache:
- bundler
- apt
services:
- elasticsearch
before_script:
- cp test/dummy/.env.example test/dummy/.env
- bundle exec rake app:db:setup
- bundle exec rake app:index:reset
addons:
  apt:
    sources:
    - elasticsearch-2.1
    packages:
    - elasticsearch
